"""
Numerical parity of pvclust_py.msfit against R's pvclust:::msfit.

This is the highest-value test in the suite. ``msfit`` is deterministic given
(bp, r, nboot) -- no RNG -- so agreement with R is exact rather than statistical,
and any divergence here is a real bug rather than Monte Carlo noise.

Fixtures are generated by scripts/make_fixtures.R against pvclust 2.2-0 and are
committed, so CI never needs R. Regenerate with:

    docker run --rm -v "$PWD/tests/fixtures:/fixtures" -v "$PWD/scripts:/scripts" \
      rocker/r-base:latest bash -c \
      "Rscript -e 'install.packages(\"pvclust\", repos=\"https://cloud.r-project.org\")' \
       && Rscript /scripts/make_fixtures.R"
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from pvclust_py.msfit import msfit

FIXTURES = Path(__file__).parent / "fixtures"

# R prints ~15 significant digits; this is as tight as the round-trip through CSV allows.
RTOL = 1e-8
ATOL = 1e-10

# msfit field  ->  column name in the R fixture
FIELDS = {
    "si": "si", "au": "au", "bp": "bp",
    "se_si": "se.si", "se_au": "se.au", "se_bp": "se.bp",
    "v": "v", "c": "c",
    "df": "df", "rss": "rss", "pchi": "pchi",
}


def _compare(got, expected_row, label):
    """Assert every msfit field matches R's, reporting which field diverged."""
    for attr, col in FIELDS.items():
        if col not in expected_row:
            continue
        mine = getattr(got, attr)
        theirs = float(expected_row[col])
        np.testing.assert_allclose(
            mine, theirs, rtol=RTOL, atol=ATOL,
            err_msg=f"{label}: field {attr!r} (R column {col!r}) "
                    f"python={mine!r} R={theirs!r}",
        )


def _case_params():
    inp = pd.read_csv(FIXTURES / "msfit_cases_input.csv", float_precision="round_trip")
    exp = pd.read_csv(FIXTURES / "msfit_cases_expected.csv", float_precision="round_trip")
    out = []
    for _, e in exp.iterrows():
        g = inp[inp["case"] == e["case"]].sort_values("scale_index")
        out.append(pytest.param(e["case"], int(e["nboot"]),
                                g["bp"].to_numpy(), g["r"].to_numpy(), e,
                                id=f"{e['case']}-nboot{int(e['nboot'])}"))
    return out


@pytest.mark.parametrize("case,nboot,bp,r,expected", _case_params())
def test_msfit_synthetic_cases(case, nboot, bp, r, expected):
    """Hand-built BP curves pinning every branch, including the degenerate
    short-circuit and the eps boundaries at both ends."""
    _compare(msfit(bp, r, nboot), expected, f"case={case} nboot={nboot}")


def test_msfit_over_a_real_run():
    """Every edge of a real pvclust run on lung[1:100, 1:20].

    Low nboot on purpose: it yields many degenerate edges (BP pinned at 1.0 across
    all scales), which is exactly where the port is most likely to diverge.
    """
    count = pd.read_csv(FIXTURES / "run_count.csv", index_col=0, float_precision="round_trip")
    scales = pd.read_csv(FIXTURES / "run_scales.csv", float_precision="round_trip")
    expected = pd.read_csv(FIXTURES / "run_edges_expected.csv", index_col=0, float_precision="round_trip")

    r = scales["r"].to_numpy()
    nboot = scales["nboot"].to_numpy()

    assert len(count) == len(expected), "fixture mismatch: edges vs expected rows"

    for edge_id, row in count.iterrows():
        bp = row.to_numpy(dtype=float) / nboot
        _compare(msfit(bp, r, nboot), expected.loc[edge_id], f"edge={edge_id}")


def test_degenerate_edges_are_present_in_the_fixture():
    """Guard the guard: if the fixture ever stops containing degenerate edges,
    test_msfit_over_a_real_run silently stops covering that branch."""
    expected = pd.read_csv(FIXTURES / "run_edges_expected.csv", index_col=0, float_precision="round_trip")
    degenerate = (expected["df"] == 0) & (expected["rss"] == 0)
    assert degenerate.any(), "fixture no longer exercises the degenerate branch"

def test_msfit_over_a_run_with_quantised_scales():
    """Per-edge parity on a run whose effective r values are the awkward quantised
    ones (0.492063, 0.587302, ...) rather than clean tenths."""
    count = pd.read_csv(FIXTURES / "run63_count.csv", index_col=0, float_precision="round_trip")
    scales = pd.read_csv(FIXTURES / "run63_scales.csv", float_precision="round_trip")
    expected = pd.read_csv(FIXTURES / "run63_edges_expected.csv", index_col=0, float_precision="round_trip")

    r = scales["effective_r"].to_numpy()
    nboot = scales["nboot"].to_numpy()
    assert not np.allclose(r, np.arange(0.5, 1.45, 0.1)), "fixture must use quantised r"

    for edge_id, row in count.iterrows():
        bp = row.to_numpy(dtype=float) / nboot
        _compare(msfit(bp, r, nboot), expected.loc[edge_id], f"n63 edge={edge_id}")
