"""Generate the two demo notebooks. Kept as a script so the notebooks are
reproducible artifacts rather than hand-edited JSON that drifts."""
import json
from pathlib import Path

def md(*lines):  return {"cell_type": "markdown", "metadata": {}, "source": "\n".join(lines)}
def code(*lines): return {"cell_type": "code", "execution_count": None, "metadata": {},
                          "outputs": [], "source": "\n".join(lines)}

def write(path, cells, title):
    nb = {"cells": cells, "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.12"}},
          "nbformat": 4, "nbformat_minor": 5}
    Path(path).write_text(json.dumps(nb, indent=1))
    print(f"wrote {path}  ({len(cells)} cells)  {title}")

# ============================================================ NOTEBOOK 1
n1 = [
md("# 1 — Clustering within a cohort",
   "",
   "Hierarchical clustering and k-means, **each with AU *p*-values**, run separately",
   "inside each cohort. This is day one: every cohort works alone.",
   "",
   "The question this notebook answers is not *what are the clusters* — any method will",
   "hand you clusters. It is **which of them are real**.",
   "",
   "| | gives you clusters | tells you if they're real |",
   "|---|---|---|",
   "| k-means | ✅ (you pick k) | ❌ |",
   "| hclust | ✅ (you pick the cut) | ❌ |",
   "| **pvclust** | ✅ | ✅ AU *p*-value per cluster |"),
code("import warnings",
     "import numpy as np, pandas as pd",
     "import matplotlib.pyplot as plt",
     "from scipy.cluster.hierarchy import dendrogram",
     "",
     "from pvclust_py.core import pvclust, kmeans_pv, pvpick",
     "from pvclust_py.datasets import load_cohorts",
     "",
     "pd.set_option('display.width', 120)",
     "",
     "# Set the clustering configuration ONCE, here.",
     "# minkowski + ward.D2 is the pairing carried over from microarray/RNAseq work.",
     "# In pvclust, minkowski means p=2 -- i.e. euclidean -- because dist.pvclust never",
     "# forwards p to R's dist(). Verified against R: max difference 0.0. Conveniently,",
     "# that also means it pools exactly under federation.",
     "METHOD_DIST = 'minkowski'",
     "METHOD_HCLUST = 'ward.D2'"),
md("## Your data goes here",
   "",
   "`load_cohorts()` splits a demo matrix by rows. **Swap in your own** — the only",
   "requirement is the orientation:",
   "",
   "- **rows = resampling units** (samples / patients)",
   "- **columns = the objects being clustered** (proteins for SomaScan, genes for RNAseq)",
   "",
   "If your matrix is the other way round, pass `df.T`. This matters: the bootstrap",
   "resamples rows, so rows must be things you could have drawn more of."),
code("cohorts = load_cohorts(n_cohorts=3)",
     "",
     "# --- to use your own data instead, replace the above with something like: -----",
     "# soma = pd.read_csv('somascan.csv', index_col=0)   # rows=samples, cols=proteins",
     "# cohorts = {'cohort_A': soma[soma.arm == 'A'].drop(columns='arm'), ...}",
     "",
     "for name, df in cohorts.items():",
     "    print(f'{name}: {df.shape[0]} samples x {df.shape[1]} objects to cluster')"),
md("## Hierarchical clustering with AU",
   "",
   "`nboot=1000` is R's default. Lower it while exploring — it is the whole cost."),
code("NBOOT = 200   # raise to 1000 (R's default) for real results",
     "",
     "results = {}",
     "for name, df in cohorts.items():",
     "    with warnings.catch_warnings():",
     "        warnings.simplefilter('ignore')",
     "        results[name] = pvclust(df.to_numpy(float), list(df.columns),",
     "                                method_dist=METHOD_DIST, method_hclust=METHOD_HCLUST,",
     "                                nboot=NBOOT, seed=42)",
     "    print(f'{name}: {len(results[name].edges)} clusters evaluated')"),
md("### AU vs BP — why this is not just a bootstrapped tree",
   "",
   "`BP` is the ordinary bootstrap number: *how often did this cluster reappear?*",
   "It is **biased downward**. `AU` removes that bias.",
   "",
   "Watch the gap in the table below. Anything where AU is high and BP is low is a",
   "real cluster that a plain bootstrap would have told you to throw away."),
code("r = results['cohort_A']",
     "tab = r.edges_frame()[['n_members', 'bp', 'au', 'si', 'se_au', 'pchi']]",
     "tab = tab.sort_values('au', ascending=False)",
     "tab['au_minus_bp'] = tab['au'] - tab['bp']",
     "tab.head(10)"),
md("**`pchi` is the honesty check.** It is a goodness-of-fit for the curve AU is read",
   "off. A small `pchi` means the model did not describe the data and the AU on that",
   "row should not be trusted, however attractive it looks."),
md("## Choosing clusters without choosing k",
   "",
   "`pvpick` returns the significant clusters. You supply a *confidence* threshold,",
   "not a number of clusters — the tree cuts itself."),
code("for name, res in results.items():",
     "    picked = pvpick(res, alpha=0.95, use='au')",
     "    print(f'\\n{name}: {len(picked)} clusters at AU >= 0.95')",
     "    for e in picked:",
     "        print(f\"   AU={e['au']:.3f}  BP={e['bp']:.3f}  n={e['n_members']:2d}  \"",
     "              f\"{', '.join(e['members'][:3])}{'...' if e['n_members'] > 3 else ''}\")"),
md("### The effect of your choices",
   "",
   "Every knob moves the answer. Look before you settle on one."),
code("df = cohorts['cohort_A']",
     "rows = []",
     "for dist in ['minkowski', 'correlation', 'abscor']:",
     "    for link in ['ward.D2', 'average']:",
     "        with warnings.catch_warnings():",
     "            warnings.simplefilter('ignore')",
     "            res = pvclust(df.to_numpy(float), list(df.columns), method_dist=dist,",
     "                          method_hclust=link, nboot=200, seed=42)",
     "        rows.append({'distance': dist, 'linkage': link,",
     "                     'clusters at AU>=0.95': len(pvpick(res, 0.95)),",
     "                     'max AU': max(e['au'] for e in res.edges[:-1])})",
     "pd.DataFrame(rows)"),
code("# nboot buys precision, and costs time. se_au shows what you are buying.",
     "rows = []",
     "for nb in [100, 250, 500, 1000]:",
     "    with warnings.catch_warnings():",
     "        warnings.simplefilter('ignore')",
     "        res = pvclust(df.to_numpy(float), list(df.columns), nboot=nb, seed=42)",
     "    fitted = [e for e in res.edges if e['df'] > 0]",
     "    rows.append({'nboot': nb, 'median se_au': np.median([e['se_au'] for e in fitted]),",
     "                 'clusters at AU>=0.95': len(pvpick(res, 0.95))})",
     "pd.DataFrame(rows)"),
md("## The dendrogram, labelled with AU"),
code("res = results['cohort_A']",
     "fig, ax = plt.subplots(figsize=(11, 5))",
     "dd = dendrogram(res.linkage, labels=res.labels, ax=ax, color_threshold=0,",
     "                above_threshold_color='#555555')",
     "for e in res.edges[:-1]:",
     "    if e['au'] >= 0.95:",
     "        ax.plot([], [], ' ')  # legend placeholder",
     "ax.set_title(f'cohort_A — {METHOD_DIST} / {METHOD_HCLUST}', fontweight='bold')",
     "ax.set_ylabel('distance')",
     "plt.setp(ax.get_xticklabels(), rotation=90, fontsize=8)",
     "plt.tight_layout(); plt.show()",
     "",
     "print('Clusters at AU >= 0.95:')",
     "for e in pvpick(res, 0.95):",
     "    print(f\"  AU={e['au']:.3f}  {', '.join(e['members'])}\")"),
md("## k-means, with the same AU treatment",
   "",
   "`msfit` never asks where a cluster came from — only whether it is present or",
   "absent in each bootstrap replicate. A k-means cluster qualifies, so k-means gets",
   "AU *p*-values from the identical machinery.",
   "",
   "Naming clusters by their **member set** also disposes of k-means' usual nuisance:",
   "cluster labels are arbitrarily permuted between runs, which stops mattering once",
   "a cluster is identified by what is in it.",
   "",
   "> **Note.** Exact member-set matching is faithful to the published framework. The",
   "> `jaccard=` option relaxes it (common practice for k-means stability) but changes",
   "> the estimand — it is then no longer the AU *p*-value as published. Say which you used."),
code("for k in [2, 3, 4]:",
     "    km = kmeans_pv(df.to_numpy(float), list(df.columns), k=k, nboot=200, seed=42)",
     "    print(f'k={k}')",
     "    for e in sorted(km.edges, key=lambda e: -e['au']):",
     "        print(f\"   AU={e['au']:.3f}  BP={e['bp']:.3f}  n={e['n_members']:2d}\")"),
md("### Which k is best supported?",
   "",
   "Instead of an elbow plot, ask which k produces clusters that survive resampling."),
code("rows = []",
     "for k in range(2, 7):",
     "    km = kmeans_pv(df.to_numpy(float), list(df.columns), k=k, nboot=200, seed=42)",
     "    aus = [e['au'] for e in km.edges]",
     "    rows.append({'k': k, 'min AU': min(aus), 'median AU': float(np.median(aus)),",
     "                 'clusters AU>=0.95': sum(a >= 0.95 for a in aus)})",
     "pd.DataFrame(rows)"),
md("---",
   "**Next:** `across_cohorts` pools these cohorts. Each ships only aggregate summaries —",
   "no sample-level rows — and the combined result is compared against what each",
   "cohort could see alone."),
]
write("ipynb/within_cohort.ipynb", n1, "within-cohort clustering")

# ============================================================ NOTEBOOK 2
n2 = [
md("# 2 — Across cohorts: federated clustering",
   "",
   "Day two. Each cohort clustered alone in notebook 1; now they combine **without",
   "any of them sharing sample-level rows**.",
   "",
   "Two things pool, by two different rules:",
   "",
   "| what pools | rule | gives |",
   "|---|---|---|",
   "| sufficient statistics | **add** four `p×p` matrices | the federated **tree** — exact |",
   "| bootstrap counts | **sum / concatenate** tallies | the federated **AU** |",
   "",
   "They are independent. The first is exact: adding statistics reproduces the",
   "distance matrix of the pooled raw data bit for bit, so the federated dendrogram",
   "*is* the centralised dendrogram."),
code("import warnings",
     "import numpy as np, pandas as pd",
     "",
     "from pvclust_py.core import pvclust, count_edges",
     "from pvclust_py.datasets import load_lung, load_cohorts",
     "from pvclust_py.distance import pairwise_stats, distance",
     "from pvclust_py.hclust import edge_table, linkage",
     "from pvclust_py.aggregate import (shared_features, federated_tree, pool_counts,",
     "                                  federated_edges, consensus_clusters)",
     "",
     "warnings.simplefilter('ignore')",
     "",
     "# Chosen once, and used for the federated tree AND the centralised comparison.",
     "# They must match, or the two are not comparable.",
     "METHOD_DIST = 'minkowski'",
     "METHOD_HCLUST = 'ward.D2'",
     "",
     "cohorts = load_cohorts(n_cohorts=3)",
     "{k: v.shape for k, v in cohorts.items()}"),
md("## Step 1 — the shared vocabulary",
   "",
   "Clustering federates only over objects every cohort measures. For a SomaScan panel",
   "this is nearly free; for RNAseq it means an explicit gene-ID intersection."),
code("shared = shared_features(df.columns for df in cohorts.values())",
     "print(f'{len(shared)} shared objects')",
     "cohorts = {k: df[shared] for k, df in cohorts.items()}"),
md("## Step 2 — what actually leaves each cohort",
   "",
   "Four `p×p` matrices, every entry a sum over rows. No row survives individually,",
   "and the payload does **not** grow with the number of samples a cohort holds."),
code("stats = {name: pairwise_stats(df.to_numpy(float)) for name, df in cohorts.items()}",
     "",
     "p = len(shared)",
     "for name, st in stats.items():",
     "    print(f'{name}: n={st[\"n\"]:3d} samples  ->  ships {4*p*p:,} numbers')",
     "print(f'\\npayload is 4p^2 = {4*p*p:,} regardless of n. But it is QUADRATIC in p:')",
     "for pp in [100, 1000, 5000, 7000, 20000]:",
     "    print(f'   p={pp:6,} -> {4*pp*pp*8/1e6:9,.0f} MB')",
     "print('\\nExact mode is comfortable to ~1-2k objects. Past that, use counts mode,')",
     "print('whose payload is ~p x n_scales rows instead.')"),
md("## Step 3 — the federated tree",
   "",
   "The aggregator adds the statistics. Nothing else."),
code("D_fed, Z_fed, catalogue = federated_tree(stats.values(), shared,",
     "                                         method_dist=METHOD_DIST,",
     "                                         method_hclust=METHOD_HCLUST)",
     "print(f'federated tree: {len(catalogue)} clusters')",
     "",
     "# the check that justifies calling this 'exact'",
     "full = load_lung()[shared]",
     "D_central = distance(full.to_numpy(float), METHOD_DIST)",
     "print(f'max difference from the centralised distance matrix: '",
     "      f'{np.abs(D_fed - D_central).max():.2e}')"),
md("### What each cohort could see alone",
   "",
   "This is the number that matters. Federation being *equal* to centralised is the",
   "theorem — it could hardly come out otherwise. The interesting comparison is",
   "against what a cohort sees on its own."),
code("truth = {e['edge_id'] for e in edge_table(linkage(D_central, METHOD_HCLUST), shared)}",
     "",
     "solo = {}",
     "for name, df in cohorts.items():",
     "    Z = linkage(distance(df.to_numpy(float), METHOD_DIST), METHOD_HCLUST)",
     "    solo[name] = {e['edge_id'] for e in edge_table(Z, shared)}",
     "    print(f'{name} alone: recovers {len(solo[name] & truth):2d}/{len(truth)} clusters')",
     "",
     "agree = set.intersection(*solo.values())",
     "fed = {e['edge_id'] for e in catalogue}",
     "print(f'\\nall three cohorts agree on: {len(agree):2d}/{len(truth)}')",
     "print(f'federated:                  {len(fed & truth):2d}/{len(truth)}')"),
md("## Step 4 — federated AU",
   "",
   "Now the counts. Each cohort bootstraps against the **federated catalogue** rather",
   "than its own tree — that is what makes the tallies addable. A cohort can count a",
   "cluster its own tree never produced; that is exactly the point.",
   "",
   "This is the second pass of counts-mode federation."),
code("NBOOT = 200   # raise to 1000 (R's default) for real results",
     "members = [e['members'] for e in catalogue]",
     "",
     "count_frames = []",
     "for name, df in cohorts.items():",
     "    counts, r_eff, nboot_vec, _ = count_edges(",
     "        df.to_numpy(float), members, shared, nboot=NBOOT, seed=42,",
     "        method_dist=METHOD_DIST, method_hclust=METHOD_HCLUST)",
     "    count_frames.append(pd.DataFrame([",
     "        {'edge_id': e['edge_id'], 'r': float(r_eff[j]), 'n': len(df),",
     "         'nboot': int(nboot_vec[j]), 'count': int(counts[i, j])}",
     "        for i, e in enumerate(catalogue) for j in range(len(r_eff))]))",
     "    print(f'{name}: {len(count_frames[-1]):,} count rows  '",
     "          f'(scales {r_eff.min():.3f}-{r_eff.max():.3f})')"),
md("### Scales must be put on a common footing first",
   "",
   "Each cohort's `r` is relative to **its own** n. `r = 1.0` at a 55-sample cohort",
   "means 55 rows; at a 17-sample cohort it means 17. Those are different scales, and",
   "adding their counts as though they matched would be wrong.",
   "",
   "`pool_counts` re-expresses every measurement against the pooled n:",
   "",
   "```",
   "size     = r_cohort x n_cohort        # absolute rows drawn",
   "r_pooled = size / sum(n_cohort)",
   "```",
   "",
   "**And here is the open question.** After rescaling, no cohort can reach",
   "`r_pooled = 1` — none of them holds all the rows. So the pooled scatter has more",
   "points across a wider spread, but sits *below* 1, which makes the extrapolation to",
   "σ² = −1 longer than a centralised run would need.",
   "",
   "More scales and wider spread help condition the two-parameter fit; a longer",
   "extrapolation hurts. Which wins is **not settled here**, and the printout below is",
   "the evidence you would need to start answering it."),
code("pooled = pool_counts(count_frames)   # rescales to the pooled n by default",
     "",
     "n_total = sum(len(df) for df in cohorts.values())",
     "print(f'pooled n = {n_total}\\n')",
     "print('as each cohort sees it (r relative to its own n):')",
     "for f, (name, df) in zip(count_frames, cohorts.items()):",
     "    print(f'  {name} (n={len(df):2d}): r {f.r.min():.3f}-{f.r.max():.3f}, '",
     "          f'absolute {int(f.r.min()*len(df))}-{int(f.r.max()*len(df))} rows')",
     "print('\\nafter rescaling to the pooled n:')",
     "print(f'  POOLED: r {pooled.r.min():.3f}-{pooled.r.max():.3f} '",
     "      f'({pooled.r.nunique()} distinct scales vs {count_frames[0].r.nunique()} per cohort)')",
     "print(f'  reaches r=1? {pooled.r.max() >= 1.0}   <-- the open question above')"),
code("fed_edges = federated_edges(pooled, catalogue)",
     "fed_edges[['n_members', 'bp', 'au', 'si', 'se_au', 'pchi', 'n_scales']].head(10)"),
md("### Federated AU vs going it alone"),
code("solo_au = {}",
     "for name, df in cohorts.items():",
     "    res = pvclust(df.to_numpy(float), shared, nboot=NBOOT, seed=42,",
     "                  method_dist=METHOD_DIST, method_hclust=METHOD_HCLUST)",
     "    solo_au[name] = {e['edge_id']: e['au'] for e in res.edges}",
     "",
     "cmp = fed_edges[['edge_id', 'n_members', 'au']].rename(columns={'au': 'au_federated'})",
     "for name in cohorts:",
     "    cmp[f'au_{name}'] = cmp.edge_id.map(solo_au[name])",
     "cmp.head(10)"),
md("**Blank cells are the point.** A missing value means that cohort's own tree never",
   "produced the cluster, so alone it had nothing to report. The federation gives it",
   "an answer."),
md("## Step 5 — the consensus set"),
code("cons = consensus_clusters(fed_edges, alpha=0.95)",
     "print(f'{len(cons)} clusters at federated AU >= 0.95:')",
     "for e in cons:",
     "    print(f\"  AU={e['au']:.3f}  BP={e['bp']:.3f}  n={e['n_members']}  \"",
     "          f\"{', '.join(e['_members'][:3])}{'...' if e['n_members'] > 3 else ''}\")"),
md("## What goes back to each project",
   "",
   "| artifact | contents |",
   "|---|---|",
   "| `shared_features.csv` | the shared vocabulary |",
   "| `federated_distance.csv` | pooled `p×p` |",
   "| `federated_tree.json` | the pooled dendrogram |",
   "| `federated_pvclust_edges.csv` | per cluster: si, au, bp, se, v, c, pchi |",
   "",
   "### And what a project does with them",
   "",
   "**Not** shared patients — patients are disjoint across projects, so there is no",
   "shared object set and patient clusters have nothing to pool. What federates is the",
   "**feature space**: the analyte modules validated across every cohort's samples.",
   "",
   "A project then clusters *its own* patients in that validated space. Endotypes stay",
   "local; the space they are discovered in has the whole federation behind it. Cohort",
   "demographics characterise the endotypes afterwards rather than driving them."),
code("# each cluster that survived federation becomes one module score per sample",
     "modules = {e['edge_id']: e['_members'] for e in cons}",
     "local = cohorts['cohort_A']",
     "scores = pd.DataFrame({f'module_{i+1}': local[m].mean(axis=1)",
     "                       for i, m in enumerate(modules.values())})",
     "print(f'cohort_A: {scores.shape[0]} samples described by {scores.shape[1]} '",
     "      f'federation-validated modules instead of {len(shared)} raw objects')",
     "scores.head()"),
md("---",
   "That reduced, validated matrix is where patient-level endotype clustering happens —",
   "with `pvclust` or `kmeans_pv` from notebook 1, run locally.",
   "",
   "**One caveat to carry forward.** Clustering patients means resampling analytes, and",
   "analytes are co-expressed rather than independent, so AU there is anti-conservative.",
   "It is a real number, but it is optimistic. Report it as such."),
]
write("ipynb/across_cohorts.ipynb", n2, "federated clustering")
