"""Generate the two demo notebooks. Kept as a script so the notebooks are
reproducible artifacts rather than hand-edited JSON that drifts."""
import json
from pathlib import Path

def md(*lines):  return {"cell_type": "markdown", "metadata": {}, "source": "\n".join(lines)}
def code(*lines): return {"cell_type": "code", "execution_count": None, "metadata": {},
                          "outputs": [], "source": "\n".join(lines)}

def write(path, cells, title):
    nb = {"cells": cells, "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.12"}},
          "nbformat": 4, "nbformat_minor": 5}
    Path(path).write_text(json.dumps(nb, indent=1))
    print(f"wrote {path}  ({len(cells)} cells)  {title}")

# ============================================================ NOTEBOOK 1
n1 = [
md("# 1 — Clustering within a cohort",
   "",
   "Hierarchical clustering and k-means, **each with AU *p*-values**, run separately",
   "inside each cohort. This is day one: every cohort works alone.",
   "",
   "The question this notebook answers is not *what are the clusters* — any method will",
   "hand you clusters. It is **which of them are real**.",
   "",
   "| | gives you clusters | tells you if they're real |",
   "|---|---|---|",
   "| k-means | ✅ (you pick k) | ❌ |",
   "| hclust | ✅ (you pick the cut) | ❌ |",
   "| **pvclust** | ✅ | ✅ AU *p*-value per cluster |"),
code("import warnings",
     "import numpy as np, pandas as pd",
     "import matplotlib.pyplot as plt",
     "from scipy.cluster.hierarchy import dendrogram",
     "",
     "from pvclust_py.core import pvclust, kmeans_pv, pvpick",
     "from pvclust_py.datasets import load_cohorts",
     "",
     "pd.set_option('display.width', 120)",
     "",
     "# Set the clustering configuration ONCE, here.",
     "# minkowski + ward.D2 is the pairing carried over from microarray/RNAseq work.",
     "# In pvclust, minkowski means p=2 -- i.e. euclidean -- because dist.pvclust never",
     "# forwards p to R's dist(). Verified against R: max difference 0.0. Conveniently,",
     "# that also means it pools exactly under federation.",
     "METHOD_DIST = 'minkowski'",
     "METHOD_HCLUST = 'ward.D2'"),
md("## Your data goes here",
   "",
   "`load_cohorts()` splits a demo matrix by rows. **Swap in your own** — the only",
   "requirement is the orientation:",
   "",
   "- **rows = resampling units** (samples / patients)",
   "- **columns = the objects being clustered** (proteins for SomaScan, genes for RNAseq)",
   "",
   "If your matrix is the other way round, pass `df.T`. This matters: the bootstrap",
   "resamples rows, so rows must be things you could have drawn more of."),
code("cohorts = load_cohorts(n_cohorts=3)",
     "",
     "# --- to use your own data instead, replace the above with something like: -----",
     "# soma = pd.read_csv('somascan.csv', index_col=0)   # rows=samples, cols=proteins",
     "# cohorts = {'cohort_A': soma[soma.arm == 'A'].drop(columns='arm'), ...}",
     "",
     "for name, df in cohorts.items():",
     "    print(f'{name}: {df.shape[0]} samples x {df.shape[1]} objects to cluster')"),
md("## Hierarchical clustering with AU",
   "",
   "`nboot=1000` is R's default. Lower it while exploring — it is the whole cost."),
code("NBOOT = 200   # raise to 1000 (R's default) for real results",
     "",
     "results = {}",
     "for name, df in cohorts.items():",
     "    with warnings.catch_warnings():",
     "        warnings.simplefilter('ignore')",
     "        results[name] = pvclust(df.to_numpy(float), list(df.columns),",
     "                                method_dist=METHOD_DIST, method_hclust=METHOD_HCLUST,",
     "                                nboot=NBOOT, seed=42)",
     "    print(f'{name}: {len(results[name].edges)} clusters evaluated')"),
md("### AU vs BP — why this is not just a bootstrapped tree",
   "",
   "`BP` is the ordinary bootstrap number: *how often did this cluster reappear?*",
   "It is **biased downward**. `AU` removes that bias.",
   "",
   "Watch the gap in the table below. Anything where AU is high and BP is low is a",
   "real cluster that a plain bootstrap would have told you to throw away."),
code("r = results['cohort_A']",
     "tab = r.edges_frame()[['n_members', 'bp', 'au', 'si', 'se_au', 'pchi']]",
     "tab = tab.sort_values('au', ascending=False)",
     "tab['au_minus_bp'] = tab['au'] - tab['bp']",
     "tab.head(10)"),
md("**`pchi` is the honesty check.** It is a goodness-of-fit for the curve AU is read",
   "off. A small `pchi` means the model did not describe the data and the AU on that",
   "row should not be trusted, however attractive it looks."),
md("## Choosing clusters without choosing k",
   "",
   "`pvpick` returns the significant clusters. You supply a *confidence* threshold,",
   "not a number of clusters — the tree cuts itself."),
code("for name, res in results.items():",
     "    picked = pvpick(res, alpha=0.95, use='au')",
     "    print(f'\\n{name}: {len(picked)} clusters at AU >= 0.95')",
     "    for e in picked:",
     "        print(f\"   AU={e['au']:.3f}  BP={e['bp']:.3f}  n={e['n_members']:2d}  \"",
     "              f\"{', '.join(e['members'][:3])}{'...' if e['n_members'] > 3 else ''}\")"),
md("### The effect of your choices",
   "",
   "Every knob moves the answer. Look before you settle on one."),
code("df = cohorts['cohort_A']",
     "rows = []",
     "for dist in ['minkowski', 'correlation', 'abscor']:",
     "    for link in ['ward.D2', 'average']:",
     "        with warnings.catch_warnings():",
     "            warnings.simplefilter('ignore')",
     "            res = pvclust(df.to_numpy(float), list(df.columns), method_dist=dist,",
     "                          method_hclust=link, nboot=200, seed=42)",
     "        rows.append({'distance': dist, 'linkage': link,",
     "                     'clusters at AU>=0.95': len(pvpick(res, 0.95)),",
     "                     'max AU': max(e['au'] for e in res.edges[:-1])})",
     "pd.DataFrame(rows)"),
code("# nboot buys precision, and costs time. se_au shows what you are buying.",
     "rows = []",
     "for nb in [100, 250, 500, 1000]:",
     "    with warnings.catch_warnings():",
     "        warnings.simplefilter('ignore')",
     "        res = pvclust(df.to_numpy(float), list(df.columns), nboot=nb, seed=42)",
     "    fitted = [e for e in res.edges if e['df'] > 0]",
     "    rows.append({'nboot': nb, 'median se_au': np.median([e['se_au'] for e in fitted]),",
     "                 'clusters at AU>=0.95': len(pvpick(res, 0.95))})",
     "pd.DataFrame(rows)"),
md("## The dendrogram, labelled with AU"),
code("res = results['cohort_A']",
     "fig, ax = plt.subplots(figsize=(11, 5))",
     "dd = dendrogram(res.linkage, labels=res.labels, ax=ax, color_threshold=0,",
     "                above_threshold_color='#555555')",
     "for e in res.edges[:-1]:",
     "    if e['au'] >= 0.95:",
     "        ax.plot([], [], ' ')  # legend placeholder",
     "ax.set_title(f'cohort_A — {METHOD_DIST} / {METHOD_HCLUST}', fontweight='bold')",
     "ax.set_ylabel('distance')",
     "plt.setp(ax.get_xticklabels(), rotation=90, fontsize=8)",
     "plt.tight_layout(); plt.show()",
     "",
     "print('Clusters at AU >= 0.95:')",
     "for e in pvpick(res, 0.95):",
     "    print(f\"  AU={e['au']:.3f}  {', '.join(e['members'])}\")"),
md("## k-means, with the same AU treatment",
   "",
   "`msfit` never asks where a cluster came from — only whether it is present or",
   "absent in each bootstrap replicate. A k-means cluster qualifies, so k-means gets",
   "AU *p*-values from the identical machinery.",
   "",
   "Naming clusters by their **member set** also disposes of k-means' usual nuisance:",
   "cluster labels are arbitrarily permuted between runs, which stops mattering once",
   "a cluster is identified by what is in it.",
   "",
   "> **Note.** Exact member-set matching is faithful to the published framework. The",
   "> `jaccard=` option relaxes it (common practice for k-means stability) but changes",
   "> the estimand — it is then no longer the AU *p*-value as published. Say which you used."),
code("for k in [2, 3, 4]:",
     "    km = kmeans_pv(df.to_numpy(float), list(df.columns), k=k, nboot=200, seed=42)",
     "    print(f'k={k}')",
     "    for e in sorted(km.edges, key=lambda e: -e['au']):",
     "        print(f\"   AU={e['au']:.3f}  BP={e['bp']:.3f}  n={e['n_members']:2d}\")"),
md("### Which k is best supported?",
   "",
   "Instead of an elbow plot, ask which k produces clusters that survive resampling."),
code("rows = []",
     "for k in range(2, 7):",
     "    km = kmeans_pv(df.to_numpy(float), list(df.columns), k=k, nboot=200, seed=42)",
     "    aus = [e['au'] for e in km.edges]",
     "    rows.append({'k': k, 'min AU': min(aus), 'median AU': float(np.median(aus)),",
     "                 'clusters AU>=0.95': sum(a >= 0.95 for a in aus)})",
     "pd.DataFrame(rows)"),
md("---",
   "**Next:** `across_cohorts` pools these cohorts. Each ships only aggregate summaries —",
   "no sample-level rows — and the combined result is compared against what each",
   "cohort could see alone."),
]
write("ipynb/within_cohort.ipynb", n1, "within-cohort clustering")

# ============================================================ NOTEBOOK 2
n2 = [
md("# 2 — Across cohorts: federated clustering",
   "",
   "Day two. Each cohort clustered alone in notebook 1; now they combine **without",
   "any of them sharing sample-level rows**.",
   "",
   "Two things pool, by two different rules:",
   "",
   "| what pools | rule | gives |",
   "|---|---|---|",
   "| sufficient statistics | **add** four `p×p` matrices | the federated **tree** — exact |",
   "| bootstrap counts | **sum / concatenate** tallies | the federated **AU** |",
   "",
   "They are independent. The first is exact: adding statistics reproduces the",
   "distance matrix of the pooled raw data bit for bit, so the federated dendrogram",
   "*is* the centralised dendrogram."),
code("import warnings",
     "import numpy as np, pandas as pd",
     "",
     "from pvclust_py.core import pvclust, count_edges",
     "from pvclust_py.datasets import load_lung, load_cohorts",
     "from pvclust_py.distance import pairwise_stats, distance",
     "from pvclust_py.hclust import edge_table, linkage",
     "from pvclust_py.aggregate import (shared_features, federated_tree, pool_counts,",
     "                                  federated_edges, consensus_clusters)",
     "",
     "warnings.simplefilter('ignore')",
     "",
     "# Chosen once, and used for the federated tree AND the centralised comparison.",
     "# They must match, or the two are not comparable.",
     "METHOD_DIST = 'minkowski'",
     "METHOD_HCLUST = 'ward.D2'",
     "",
     "cohorts = load_cohorts(n_cohorts=3)",
     "{k: v.shape for k, v in cohorts.items()}"),
md("## Step 1 — the shared vocabulary",
   "",
   "Clustering federates only over objects every cohort measures. For a SomaScan panel",
   "this is nearly free; for RNAseq it means an explicit gene-ID intersection."),
code("shared = shared_features(df.columns for df in cohorts.values())",
     "print(f'{len(shared)} shared objects')",
     "cohorts = {k: df[shared] for k, df in cohorts.items()}"),
md("## Step 2 — what actually leaves each cohort",
   "",
   "Four `p×p` matrices, every entry a sum over rows. No row survives individually,",
   "and the payload does **not** grow with the number of samples a cohort holds."),
code("stats = {name: pairwise_stats(df.to_numpy(float)) for name, df in cohorts.items()}",
     "",
     "p = len(shared)",
     "for name, st in stats.items():",
     "    print(f'{name}: n={st[\"n\"]:3d} samples  ->  ships {4*p*p:,} numbers')",
     "print(f'\\npayload is 4p^2 = {4*p*p:,} regardless of n. But it is QUADRATIC in p:')",
     "for pp in [100, 1000, 5000, 7000, 20000]:",
     "    print(f'   p={pp:6,} -> {4*pp*pp*8/1e6:9,.0f} MB')",
     "print('\\nExact mode is comfortable to ~1-2k objects. Past that, use counts mode,')",
     "print('whose payload is ~p x n_scales rows instead.')"),
md("## Step 3 — the federated tree",
   "",
   "The aggregator adds the statistics. Nothing else."),
code("D_fed, Z_fed, catalogue = federated_tree(stats.values(), shared,",
     "                                         method_dist=METHOD_DIST,",
     "                                         method_hclust=METHOD_HCLUST)",
     "print(f'federated tree: {len(catalogue)} clusters')",
     "",
     "# the check that justifies calling this 'exact'",
     "full = load_lung()[shared]",
     "D_central = distance(full.to_numpy(float), METHOD_DIST)",
     "print(f'max difference from the centralised distance matrix: '",
     "      f'{np.abs(D_fed - D_central).max():.2e}')"),
md("### What each cohort could see alone",
   "",
   "This is the number that matters. Federation being *equal* to centralised is the",
   "theorem — it could hardly come out otherwise. The interesting comparison is",
   "against what a cohort sees on its own."),
code("truth = {e['edge_id'] for e in edge_table(linkage(D_central, METHOD_HCLUST), shared)}",
     "",
     "solo = {}",
     "for name, df in cohorts.items():",
     "    Z = linkage(distance(df.to_numpy(float), METHOD_DIST), METHOD_HCLUST)",
     "    solo[name] = {e['edge_id'] for e in edge_table(Z, shared)}",
     "    print(f'{name} alone: recovers {len(solo[name] & truth):2d}/{len(truth)} clusters')",
     "",
     "agree = set.intersection(*solo.values())",
     "fed = {e['edge_id'] for e in catalogue}",
     "print(f'\\nall three cohorts agree on: {len(agree):2d}/{len(truth)}')",
     "print(f'federated:                  {len(fed & truth):2d}/{len(truth)}')"),
md("## Step 4 — federated AU",
   "",
   "Now the counts. Each cohort bootstraps against the **federated catalogue** rather",
   "than its own tree — that is what makes the tallies addable. A cohort can count a",
   "cluster its own tree never produced; that is exactly the point.",
   "",
   "This is the second pass of counts-mode federation."),
code("NBOOT = 200   # raise to 1000 (R's default) for real results",
     "members = [e['members'] for e in catalogue]",
     "",
     "count_frames = []",
     "for name, df in cohorts.items():",
     "    counts, r_eff, nboot_vec, _ = count_edges(",
     "        df.to_numpy(float), members, shared, nboot=NBOOT, seed=42,",
     "        method_dist=METHOD_DIST, method_hclust=METHOD_HCLUST)",
     "    count_frames.append(pd.DataFrame([",
     "        {'edge_id': e['edge_id'], 'r': float(r_eff[j]), 'n': len(df),",
     "         'nboot': int(nboot_vec[j]), 'count': int(counts[i, j])}",
     "        for i, e in enumerate(catalogue) for j in range(len(r_eff))]))",
     "    print(f'{name}: {len(count_frames[-1]):,} count rows  '",
     "          f'(scales {r_eff.min():.3f}-{r_eff.max():.3f})')"),
md("### Scales must be put on a common footing first",
   "",
   "Each cohort's `r` is relative to **its own** n. `r = 1.0` at a 55-sample cohort",
   "means 55 rows; at a 17-sample cohort it means 17. Those are different scales, and",
   "adding their counts as though they matched would be wrong.",
   "",
   "`pool_counts` re-expresses every measurement against the pooled n:",
   "",
   "```",
   "size     = r_cohort x n_cohort        # absolute rows drawn",
   "r_pooled = size / sum(n_cohort)",
   "```",
   "",
   "**And here is the open question.** After rescaling, no cohort can reach",
   "`r_pooled = 1` — none of them holds all the rows. So the pooled scatter has more",
   "points across a wider spread, but sits *below* 1, which makes the extrapolation to",
   "σ² = −1 longer than a centralised run would need.",
   "",
   "More scales and wider spread help condition the two-parameter fit; a longer",
   "extrapolation hurts. Which wins is **not settled here**, and the printout below is",
   "the evidence you would need to start answering it."),
code("pooled = pool_counts(count_frames)   # rescales to the pooled n by default",
     "",
     "n_total = sum(len(df) for df in cohorts.values())",
     "print(f'pooled n = {n_total}\\n')",
     "print('as each cohort sees it (r relative to its own n):')",
     "for f, (name, df) in zip(count_frames, cohorts.items()):",
     "    print(f'  {name} (n={len(df):2d}): r {f.r.min():.3f}-{f.r.max():.3f}, '",
     "          f'absolute {int(f.r.min()*len(df))}-{int(f.r.max()*len(df))} rows')",
     "print('\\nafter rescaling to the pooled n:')",
     "print(f'  POOLED: r {pooled.r.min():.3f}-{pooled.r.max():.3f} '",
     "      f'({pooled.r.nunique()} distinct scales vs {count_frames[0].r.nunique()} per cohort)')",
     "print(f'  reaches r=1? {pooled.r.max() >= 1.0}   <-- the open question above')"),
code("fed_edges = federated_edges(pooled, catalogue)",
     "fed_edges[['n_members', 'bp', 'au', 'si', 'se_au', 'pchi', 'n_scales']].head(10)"),
md("### Federated AU vs going it alone"),
code("solo_au = {}",
     "for name, df in cohorts.items():",
     "    res = pvclust(df.to_numpy(float), shared, nboot=NBOOT, seed=42,",
     "                  method_dist=METHOD_DIST, method_hclust=METHOD_HCLUST)",
     "    solo_au[name] = {e['edge_id']: e['au'] for e in res.edges}",
     "",
     "cmp = fed_edges[['edge_id', 'n_members', 'au']].rename(columns={'au': 'au_federated'})",
     "for name in cohorts:",
     "    cmp[f'au_{name}'] = cmp.edge_id.map(solo_au[name])",
     "cmp.head(10)"),
md("**Blank cells are the point.** A missing value means that cohort's own tree never",
   "produced the cluster, so alone it had nothing to report. The federation gives it",
   "an answer."),
md("## Step 5 — the consensus set"),
code("cons = consensus_clusters(fed_edges, alpha=0.95)",
     "print(f'{len(cons)} clusters at federated AU >= 0.95:')",
     "for e in cons:",
     "    print(f\"  AU={e['au']:.3f}  BP={e['bp']:.3f}  n={e['n_members']}  \"",
     "          f\"{', '.join(e['_members'][:3])}{'...' if e['n_members'] > 3 else ''}\")"),
md("## What goes back to each project",
   "",
   "| artifact | contents |",
   "|---|---|",
   "| `shared_features.csv` | the shared vocabulary |",
   "| `federated_distance.csv` | pooled `p×p` |",
   "| `federated_tree.json` | the pooled dendrogram |",
   "| `federated_pvclust_edges.csv` | per cluster: si, au, bp, se, v, c, pchi |",
   "",
   "### And what a project does with them",
   "",
   "**Not** shared patients — patients are disjoint across projects, so there is no",
   "shared object set and patient clusters have nothing to pool. What federates is the",
   "**feature space**: the analyte modules validated across every cohort's samples.",
   "",
   "A project then clusters *its own* patients in that validated space. Endotypes stay",
   "local; the space they are discovered in has the whole federation behind it. Cohort",
   "demographics characterise the endotypes afterwards rather than driving them."),
code("# each cluster that survived federation becomes one module score per sample",
     "modules = {e['edge_id']: e['_members'] for e in cons}",
     "local = cohorts['cohort_A']",
     "scores = pd.DataFrame({f'module_{i+1}': local[m].mean(axis=1)",
     "                       for i, m in enumerate(modules.values())})",
     "print(f'cohort_A: {scores.shape[0]} samples described by {scores.shape[1]} '",
     "      f'federation-validated modules instead of {len(shared)} raw objects')",
     "scores.head()"),
md("---",
   "That reduced, validated matrix is where patient-level endotype clustering happens —",
   "with `pvclust` or `kmeans_pv` from notebook 1, run locally.",
   "",
   "**One caveat to carry forward.** Clustering patients means resampling analytes, and",
   "analytes are co-expressed rather than independent, so AU there is anti-conservative.",
   "It is a real number, but it is optimistic. Report it as such."),
]
write("ipynb/across_cohorts.ipynb", n2, "federated clustering")

# ============================================================ NOTEBOOK 3
# The command-line pair. Notebooks 1 and 2 call the library; these two type the same
# commands a Nextflow process would, so what you read here is what you run.

SETUP = code(
    "import os, shutil, subprocess, textwrap",
    "from pathlib import Path",
    "import numpy as np, pandas as pd",
    "import matplotlib.pyplot as plt",
    "",
    "# Everything is written here, so nothing lands in the repository.",
    "WORK = Path('sle-run'); WORK.mkdir(exist_ok=True); os.chdir(WORK)",
    "",
    "def run(cmd):",
    "    \"\"\"Run one pvclust-py command and echo it, so the notebook shows the",
    "    command line rather than hiding it behind a function.\"\"\"",
    "    print('$ ' + ' '.join(cmd if isinstance(cmd, list) else [cmd]))",
    "    r = subprocess.run(cmd, capture_output=True, text=True)",
    "    print((r.stdout + r.stderr).strip()[-1500:])",
    "    if r.returncode:",
    "        raise SystemExit(f'command failed: {cmd}')",
    "",
    "def show(png):",
    "    \"\"\"Render a written figure inline. matplotlib only, so this works in CI too.\"\"\"",
    "    if not Path(png).exists():",
    "        print(f'(missing {png})'); return",
    "    fig, ax = plt.subplots(figsize=(13, 13))",
    "    ax.imshow(plt.imread(png)); ax.axis('off'); ax.set_title(png, fontsize=9)",
    "    plt.show()")

DATA = code(
    "# The SLE data is not in the repository -- download it from Zenodo",
    "# (doi:10.5281/zenodo.20342569) and point SLE at the unpacked folder.",
    "SLE = Path(os.environ.get('SLE', '../data/SLE_doi.10.5281_zenodo_20342569'))",
    "REAL = (SLE / 'abundance.csv').exists()",
    "",
    "if REAL:",
    "    NBOOT, TOPVAR = 1000, 100",
    "    abundance = pd.read_csv(SLE / 'abundance.csv').set_index('SampleId')",
    "    meta = pd.read_csv(SLE / 'sample-metadata.csv').set_index('SampleId')",
    "    meta = meta[meta['Included_in_study'] == 'Included']",
    "    abundance = abundance.loc[meta.index]",
    "    FEATURE_MAP = str(SLE / 'feature_metadata.txt')",
    "    print(f'SLE data: {abundance.shape[0]} samples x {abundance.shape[1]} reagents')",
    "else:",
    "    # A stand-in with the same shape of problem, so every command below runs",
    "    # unchanged without the download: two batches, a case/control split, and a",
    "    # few proteins measured by more than one reagent.",
    "    NBOOT, TOPVAR = 40, 20",
    "    rng = np.random.default_rng(0)",
    "    n, p = 75, 30",
    "    ids = [f'S{i:03d}' for i in range(n)]",
    "    drivers = rng.normal(size=(n, 6))",
    "    X = np.exp(rng.normal(3, 1, size=(1, p)) + drivers @ rng.normal(size=(6, p))",
    "               + rng.normal(scale=0.3, size=(n, p)))",
    "    seqs = [f'seq.{1000+j}.{j%7}' for j in range(p)]",
    "    abundance = pd.DataFrame(X, index=pd.Index(ids, name='SampleId'), columns=seqs)",
    "    batch = np.where(np.arange(n) % 3 == 0, 'B', 'A')",
    "    abundance.loc[batch == 'B'] *= 1.6                     # a real batch shift",
    "    meta = pd.DataFrame({",
    "        'DonorId': ids, 'Batch': batch,",
    "        'Group': np.where(rng.random(n) < 0.25, 'HV', 'SLE'),",
    "        'Sex': rng.choice(['F', 'M'], n, p=[0.85, 0.15]),",
    "        'Age_group': rng.choice(['26-30', '31-35', '36-40', '41-45'], n),",
    "        'Disease_activity': rng.choice(['Remission', 'LDA', 'MDA', 'HDA'], n),",
    "        'SLEDAI_2K': rng.integers(0, 14, n)}, index=pd.Index(ids, name='SampleId'))",
    "    # names, with three proteins deliberately measured twice",
    "    gene = [f'G{j:02d}' for j in range(p)]",
    "    for a, b in [(1, 2), (10, 11), (20, 21)]:",
    "        gene[b] = gene[a]",
    "    fm = pd.DataFrame({'SeqId': seqs, 'TargetFullName': gene, 'GeneSymbol': gene})",
    "    dup = fm['GeneSymbol'].duplicated(keep=False)",
    "    fm.loc[dup, 'GeneSymbol'] = fm.loc[dup, 'GeneSymbol'] + '_' + fm.loc[dup, 'SeqId']",
    "    fm.to_csv('feature_metadata.txt', sep='\\t', index=False)",
    "    FEATURE_MAP = 'feature_metadata.txt'",
    "    print('SLE data not found -- using a stand-in of the same shape.')",
    "    print(f'stand-in: {abundance.shape[0]} samples x {abundance.shape[1]} reagents')")

SPLIT = code(
    "# Three cohorts, donors kept whole so repeat timepoints never straddle a boundary.",
    "rng = np.random.default_rng(42)",
    "donors = meta.groupby('DonorId').size().index.to_numpy()",
    "who = dict(zip(rng.permutation(donors), range(len(donors))))",
    "which = meta['DonorId'].map(lambda d: 'ABC'[who[d] % 3])",
    "",
    "# SLEDAI banded, so it reads as a strip rather than fifteen shades of one colour.",
    "out = meta.copy()",
    "out['SLEDAI_band'] = pd.cut(pd.to_numeric(out['SLEDAI_2K'], errors='coerce'),",
    "                            [-0.1, 0, 4, 8, 30], labels=['0', '1-4', '5-8', '9+'])",
    "out = out.astype({'SLEDAI_band': str}).replace('nan', 'NA').fillna('NA')",
    "out.to_csv('meta.csv')",
    "abundance.to_csv('cohort_all.csv')",
    "for c in 'ABC':",
    "    abundance.loc[which[which == c].index].to_csv(f'cohort{c}.csv')",
    "print({c: int((which == c).sum()) for c in 'ABC'})")

COMMON = code(
    "# The flags every command shares. Written out in full each time below, so you can",
    "# copy any single cell straight into a terminal.",
    "COMMON = ['--log2', '--adjust', 'combat', '--batch-col', 'Batch',",
    "          '--protect', 'Group', '--metadata', 'meta.csv',",
    "          '--shared-features', 'all_features.csv',",
    "          '--feature-map', FEATURE_MAP, '--feature-label', 'GeneSymbol']",
    "DIST = ['--dist', 'correlation', '--linkage', 'average']",
    "print(' '.join(COMMON))")

n3 = [
md("# 3 — One cohort, from the command line",
   "",
   "Notebook 1 calls the library. This one types the commands, so what you read here is",
   "what a terminal — or a Nextflow process — runs. Same clustering, same *p*-values.",
   "",
   "Both methods appear side by side: **pvclust** and **k-means**, each with AU.",
   "",
   "It runs on the SLE proteomics data if you have it, and on a stand-in of the same",
   "shape if you do not, so every cell executes either way."),
SETUP,
md("## The data",
   "",
   "Download from Zenodo (doi:10.5281/zenodo.20342569), unpack it, and point `SLE` at",
   "the folder. Without it the cells below still run, against a generated stand-in that",
   "has the same awkward features: two batches, a case/control split, and a few",
   "proteins measured by more than one reagent."),
DATA,
md("## Three cohorts",
   "",
   "Split by donor rather than by sample. A donor with two timepoints must land wholly",
   "in one cohort, or the cohorts share subjects and the federation is measuring the",
   "same person twice."),
SPLIT,
md("## Pick the objects once",
   "",
   "Every cohort has to cluster the **same** objects, or nothing pools. So the most",
   "variable proteins are chosen once, on the pooled data, and that list is handed to",
   "each cohort with `--shared-features`.",
   "",
   "Note the order inside the command: log2, then ComBat, then the variance ranking.",
   "Ranking before correcting would rank the batch shift."),
code("run(['pvclust-py', 'project-features', '--project', 'all',",
     "     '--matrix', 'cohort_all.csv', '--log2',",
     "     '--adjust', 'combat', '--batch-col', 'Batch', '--protect', 'Group',",
     "     '--metadata', 'meta.csv', '--top-variable', str(TOPVAR),",
     "     '--feature-map', FEATURE_MAP, '--feature-label', 'GeneSymbol'])"),
COMMON,
md("## pvclust, one cohort at a time",
   "",
   "`--plot` writes the dendrogram with AU in red and BP in green, and boxes the",
   "clusters that clear `--alpha`. Each cohort is corrected against **its own** batches,",
   "which is what a real site would do."),
code("for c in 'ABC':",
     "    run(['pvclust-py', 'cluster', '--project', f'cohort{c}',",
     "         '--matrix', f'cohort{c}.csv', *COMMON, *DIST,",
     "         '--n-boot', str(NBOOT), '--alpha', '0.95', '--plot'])"),
code("show('cohortA_dendrogram.png')"),
md("## k-means, with the same AU treatment",
   "",
   "`--jaccard` is not optional here. k-means has no tree, so a cluster is matched",
   "across bootstrap replicates by its membership, and demanding an *exact* member set",
   "drives BP to zero as the object count grows — 0.83 at 20 objects, 0.20 at 50, and",
   "0.00 at 150. Jaccard overlap at 0.6 is what keeps the count meaningful."),
code("for c in 'ABC':",
     "    run(['pvclust-py', 'kmeans', '--project', f'cohort{c}', '--k', '10',",
     "         '--matrix', f'cohort{c}.csv', *COMMON,",
     "         '--n-boot', str(NBOOT), '--jaccard', '0.6', '--plot'])"),
md("## The two-way figure",
   "",
   "Both axes clustered and ordered by support, with the demographics as strips down",
   "the side. This is also the batch-effect check: if the samples cluster by plate",
   "rather than by biology, the strips show it immediately.",
   "",
   "`--method` chooses which clustering orders the axes."),
code("ANN = ['--annotate', 'Group,Sex,Age_group,Disease_activity,SLEDAI_band',",
     "       '--max-rows', '400', '--max-labels', '160']",
     "run(['pvclust-py', 'heatmap', '--project', 'cohortA',",
     "     '--matrix', 'cohortA.csv', *COMMON, *DIST, '--method', 'pvclust',",
     "     '--n-boot', str(NBOOT), *ANN])"),
code("show('cohortA_heatmap_pvclust.png')"),
code("run(['pvclust-py', 'heatmap', '--project', 'cohortA',",
     "     '--matrix', 'cohortA.csv', *COMMON, *DIST, '--method', 'kmeans', '--k', '10',",
     "     '--n-boot', str(NBOOT), '--jaccard', '0.6', *ANN])"),
code("show('cohortA_heatmap_kmeans.png')"),
md("---",
   "Each cohort now has its own answer. Notebook 4 pools them without any cohort",
   "sending a single subject-level row."),
]
write("ipynb/within_cohort_cli.ipynb", n3, "one cohort, via the CLI")

# ============================================================ NOTEBOOK 4
n4 = [
md("# 4 — Federating across cohorts, from the command line",
   "",
   "Notebook 3 left three cohorts each with their own clusters. This one pools them.",
   "",
   "What crosses the boundary is **sufficient statistics** and **bootstrap counts**.",
   "No cohort ships a row. The pooled tree is nonetheless bit-for-bit the tree you",
   "would get by pooling the raw matrices.",
   "",
   "Run notebook 3 first: this one reuses the same `sle-run/` directory."),
SETUP,
DATA,
SPLIT,
code("run(['pvclust-py', 'project-features', '--project', 'all',",
     "     '--matrix', 'cohort_all.csv', '--log2',",
     "     '--adjust', 'combat', '--batch-col', 'Batch', '--protect', 'Group',",
     "     '--metadata', 'meta.csv', '--top-variable', str(TOPVAR),",
     "     '--feature-map', FEATURE_MAP, '--feature-label', 'GeneSymbol'])"),
COMMON,
md("## What actually leaves each cohort",
   "",
   "Four `p x p` matrices: pairwise counts, sums, sums of squares, and the Gram matrix.",
   "Every entry is a sum over rows, which is exactly why they add across cohorts.",
   "",
   "**The privacy rule is `p < n`.** The Gram matrix has rank `min(n, p)`, so when a",
   "cohort has fewer samples than objects its row space is fully exposed. At `n = 1` the",
   "Gram is rank one and hands back the row itself (Homer et al., 2008)."),
code("for c in 'ABC':",
     "    run(['pvclust-py', 'project-stats', '--project', f'cohort{c}',",
     "         '--matrix', f'cohort{c}.csv', *COMMON])"),
md("## Pass one: the pooled tree and the catalogue",
   "",
   "Pooling the statistics gives the exact pooled distance matrix, and from it the",
   "federated tree. Its clusters become the **catalogue** every cohort will count",
   "against."),
code("STATS = [a for c in 'ABC' for a in ('--stats', f'cohort{c}_stats.npz')]",
     "run(['pvclust-py', 'aggregate-trees', '--labels', 'cohortA_labels.txt',",
     "     *STATS, *DIST])"),
md("## Pass two: everyone counts against that one catalogue",
   "",
   "This second pass is **not optional**. Pooling per-cohort trees instead finds",
   "clusters no cohort agrees on, because each cohort's tree contains different",
   "clusters and a count only adds to another count when both describe the same",
   "member set. The catalogue is what makes the counts addable.",
   "",
   "Clusters are identified by content — a hash of the sorted member names — never by",
   "position in a tree."),
code("for c in 'ABC':",
     "    run(['pvclust-py', 'count-edges', '--project', f'cohort{c}',",
     "         '--catalogue', 'federated_pvclust_catalogue.csv',",
     "         '--matrix', f'cohort{c}.csv', *COMMON, *DIST, '--n-boot', str(NBOOT)])"),
md("## Federated AU",
   "",
   "Counts are summed and `msfit` is run once, at the aggregator, on the pooled",
   "bootstrap probabilities. Each cohort's scales are relative to its own `n`, so they",
   "are re-expressed against the pooled `n` before adding; without that rescaling the",
   "curve is fitted against the wrong abscissa and the federated AU collapses."),
code("COUNTS = [a for c in 'ABC' for a in ('--counts', f'cohort{c}_counts.csv')]",
     "run(['pvclust-py', 'aggregate-trees', '--labels', 'cohortA_labels.txt',",
     "     *STATS, *COUNTS, *DIST, '--alpha', '0.95'])"),
md("## The k-means catalogue",
   "",
   "The same pooled distance, partitioned flat instead of hierarchically. It uses",
   "**k-medoids**, because Lloyd's algorithm needs centroids — coordinates — while",
   "medoids need only distances, and distances are what federate.",
   "",
   "The outputs carry the method in their names, so this does not overwrite the",
   "pvclust catalogue."),
code("run(['pvclust-py', 'aggregate-trees', '--labels', 'cohortA_labels.txt',",
     "     *STATS, *DIST, '--partition', 'kmeans', '--k', '10'])",
     "print(sorted(p.name for p in Path('.').glob('federated_*')))"),
md("## Back to each cohort",
   "",
   "There is no single global answer. Each cohort gets **its own** outcome: its local",
   "AU for every federated cluster, next to the federated value. A cluster with high",
   "federated AU and low local AU is one this cohort could not have found alone, which",
   "is the gain from federating made concrete.",
   "",
   "`--plot` draws the cohort's own data arranged in the federation's order."),
code("for c in 'ABC':",
     "    run(['pvclust-py', 'apply-edges', '--project', f'cohort{c}',",
     "         '--matrix', f'cohort{c}.csv', *COMMON, *DIST,",
     "         '--federated-edges', 'federated_pvclust_edges.csv',",
     "         '--n-boot', str(NBOOT), '--alpha', '0.95', '--plot'])"),
code("sup = pd.read_csv('cohortA_from-federated_edge_support.csv')",
     "print('where federating helped cohort A most:')",
     "print(sup.head(8)[['n_members', 'au_local', 'au_federated', 'gain']].to_string(index=False))"),
md("## Did the tree find biology or noise?",
   "",
   "A protein measured by two reagents is a positive control with a known answer: the",
   "two must land together, or the tree is measuring noise. The permutation null asks",
   "how tight a random group of the same size would be, which turns *they are close*",
   "into a *p*-value.",
   "",
   "Not every miss is a failure. On the real data SIGLEC5 merges with its paralog",
   "SIGLEC14, whose extracellular domains are near-identical so the reagents",
   "cross-react, and SAA1 pairs with CRP because both are IL-6-driven acute-phase",
   "reactants. Those are correct answers, not clustering errors."),
code("import numpy as np",
     "from pvclust_py.core import PvclustResult",
     "from pvclust_py.hclust import linkage, edge_table",
     "from pvclust_py.validate import reagent_groups, cocluster, summary",
     "",
     "D = pd.read_csv('federated_distance.csv', index_col=0)",
     "labels = list(D.columns)",
     "au = dict(zip(*pd.read_csv('federated_pvclust_edges.csv')[['edge_id', 'au']].values.T))",
     "Z = linkage(D.to_numpy(float), 'average')",
     "edges = [dict(e, au=float(au.get(e['edge_id'], 0.0)), bp=0.0, si=0.0, se_au=0.0,",
     "              se_bp=0.0, se_si=0.0, v=0.0, c=0.0, df=0, rss=0.0, pchi=1.0)",
     "         for e in edge_table(Z, labels)]",
     "res = PvclustResult(linkage=Z, labels=labels, edges=edges,",
     "                    count=np.zeros((len(edges), 1)), r=np.array([1.0]),",
     "                    nboot=np.array([1]), method_dist='correlation',",
     "                    method_hclust='average', cluster='columns')",
     "",
     "ann = pd.read_csv(FEATURE_MAP, sep='\\t')",
     "groups = reagent_groups(labels, annotation=ann, name_col='TargetFullName')",
     "if groups:",
     "    print(summary(cocluster(res, groups, alpha=0.95)))",
     "else:",
     "    print('no protein in this feature set is measured by more than one reagent')"),
md("---",
   "**What each cohort ends up with.**",
   "",
   "| artifact | contents |",
   "|---|---|",
   "| `federated_distance.csv` | the pooled `p x p` distance |",
   "| `federated_pvclust_catalogue.csv` | clusters of the pooled tree |",
   "| `federated_kmeans_catalogue.csv` | the flat k-medoids partition |",
   "| `federated_pvclust_edges.csv` | per cluster: si, au, bp, standard errors, v, c, pchi |",
   "| `<cohort>_from-federated_edge_support.csv` | local vs federated AU, per cluster |",
   "| `<cohort>_from-federated_modules.csv` | the non-overlapping module definitions |",
   "| `<cohort>_from-federated_module_scores.csv` | one score per sample per module |",
   "",
   "**One caveat to carry forward.** Clustering patients means resampling analytes, and",
   "analytes are co-expressed rather than independent, so AU on that axis is",
   "anti-conservative. It is a real number, but an optimistic one. Report it as such."),
]
write("ipynb/across_cohorts_cli.ipynb", n4, "federation, via the CLI")
